name: 🐛 Bug Report
description: Report a bug to help us improve Kommentio
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏
        
        Please provide as much detail as possible to help us identify and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the documentation and followed the setup instructions
          required: true

  - type: input
    id: version
    attributes:
      label: Kommentio Version
      description: Which version of Kommentio are you using?
      placeholder: "e.g., v0.1.1"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you experiencing this bug?
      options:
        - Mock Mode (without Supabase)
        - Production (with Supabase)
        - Development Environment
        - Other
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: Which browser(s) are affected?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share your Kommentio configuration (remove sensitive data)
      placeholder: |
        ```html
        <div 
          data-kommentio
          data-site-id="my-blog"
          data-theme="light"
          data-language="ko"
        ></div>
        ```

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors in the browser console?
      placeholder: |
        ```
        Paste console errors here
        ```

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, network requests, etc.