blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/xavierchoi/kommentio/blob/main/README.md
    about: Read the full documentation and setup guide
  - name: 💬 Discussions
    url: https://github.com/xavierchoi/kommentio/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🚀 Demo
    url: https://xavierchoi.github.io/kommentio
    about: Try Kommentio live demo